# Generated by Django 3.0.8 on 2020-07-23 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt_decrypt_app', '0003_remove_user_favorite_encryption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='score',
        ),
    ]
