# Generated by Django 3.0.8 on 2020-07-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt_decrypt_app', '0006_auto_20200723_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
