# Generated by Django 3.0.8 on 2020-07-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt_decrypt_app', '0007_user_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_encryption',
            field=models.ForeignKey(blank=True, choices=[('CAESAR CIPHER', 'CAESAR CIPHER'), ('ATBASH CIPHER', 'ATBASH CIPHER'), ('VIGENERE CIPHER', 'VIGENERE CIPHER'), ('MORSE CODE', 'MORSE CODE'), ('NATO CODE', 'NATO CODE'), ('REVERSE CIPHER', 'REVERSE CIPHER')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='encrypt_decrypt_app.Encryption'),
        ),
    ]
