# Generated by Django 3.0.8 on 2020-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt_decrypt_app', '0009_auto_20200723_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_encryption',
            field=models.CharField(blank=True, choices=[('CAESAR CIPHER', 'Caesar Cipher'), ('ATBASH CIPHER', 'Atbash Cipher'), ('VIGENERE CIPHER', 'Vigenere Cipher'), ('MORSE CODE', 'Morse Code'), ('NATO CODE', 'Nato Code'), ('REVERSE CIPHER', 'Reverse Cipher')], max_length=150, null=True),
        ),
    ]
