# Generated by Django 3.0.8 on 2020-07-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt_decrypt_app', '0011_auto_20200723_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryption',
            name='encryption_technique',
            field=models.CharField(choices=[('Caesar Cipher', 'Caesar Cipher'), ('Atbash Cipher', 'Atbash Cipher'), ('Vigenere Cipher', 'Vigenere Cipher'), ('Morse Code', 'Morse Code'), ('NATO Code', 'NATO Code'), ('Reverse Cipher', 'Reverse Cipher')], default='Morse Code', max_length=30, verbose_name='Encryption Name'),
        ),
    ]
