# Generated by Django 3.0.8 on 2020-07-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt_decrypt_app', '0012_auto_20200723_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='CipherGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Impossible', 'Impossible')], default='Easy', max_length=30, verbose_name='Difficulty')),
                ('name', models.CharField(max_length=600)),
                ('question', models.TextField()),
                ('key', models.IntegerField(default=20, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('answer', models.TextField()),
                ('value', models.IntegerField()),
                ('encryption_sequence', models.TextField()),
            ],
        ),
    ]
