# Generated by Django 3.0.8 on 2020-07-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt_decrypt_app', '0013_ciphergame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciphergame',
            name='key',
            field=models.TextField(null=True),
        ),
    ]
