# Generated by Django 3.0.8 on 2020-07-25 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt_decrypt_app', '0014_auto_20200724_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciphergame',
            old_name='key',
            new_name='keys',
        ),
    ]
