# Generated by Django 3.0.8 on 2020-07-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt_decrypt_app', '0015_auto_20200724_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciphergame',
            name='encryptions_used',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
