# Generated by Django 3.0.8 on 2020-07-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt_decrypt_app', '0018_ciphergame_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciphergame',
            name='solved',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
