# Generated by Django 3.0.8 on 2020-07-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt_decrypt_app', '0019_auto_20200727_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, choices=[('CIPHER LORD', 'Cipher Lord'), ('SENIOR CRYPTOGRAPHER', 'Senior Cryptographer'), ('JUNIOR CRYPTOGRAPHER', 'Junior Cryptographer'), ('ANALYST', 'Analyst'), ('ROOKIE_ANALYST', 'Rookie Analyst')], max_length=150, null=True),
        ),
    ]
