# Generated by Django 3.0.8 on 2020-07-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt_decrypt_app', '0026_auto_20200731_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(blank=True, max_length=600, null=True)),
                ('user_id', models.CharField(blank=True, max_length=600, null=True)),
                ('question_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
